# Generated by Django 5.0.14 on 2026-03-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_answer_score_form_code_form_form_type_form_max_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='form',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order on frontend (1, 2, 3, etc.)'),
        ),
    ]
