# Generated by Django 5.0.14 on 2026-03-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_add_order_to_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['form_type', 'order', '-created_at']},
        ),
        migrations.AlterField(
            model_name='form',
            name='form_type',
            field=models.CharField(choices=[('assessment', 'Assessment'), ('survey', 'Survey'), ('feedback', 'Feedback'), ('pulse', 'Pulse')], default='survey', max_length=20),
        ),
        migrations.AlterField(
            model_name='form',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Display order within form type (1, 2, 3, etc.)'),
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('form_type', 'order')},
        ),
    ]
