# Generated by Django 5.0.14 on 2026-03-24 07:39

from django.db import migrations


def fix_duplicate_orders(apps, schema_editor):
    """Fix duplicate order values within each form type"""
    Form = apps.get_model('forms', 'Form')
    
    # Get all form types
    form_types = Form.objects.values_list('form_type', flat=True).distinct()
    
    for form_type in form_types:
        # Get all forms of this type ordered by creation date
        forms = Form.objects.filter(form_type=form_type).order_by('created_at')
        
        # Assign sequential order numbers
        for index, form in enumerate(forms, start=1):
            form.order = index
            form.save()


def reverse_fix_duplicate_orders(apps, schema_editor):
    """Reverse operation - set all orders back to 0"""
    Form = apps.get_model('forms', 'Form')
    Form.objects.all().update(order=0)


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_update_form_ordering_by_type'),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_orders, reverse_fix_duplicate_orders),
    ]