# Generated by Django 5.0.14 on 2026-03-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_fix_duplicate_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='type',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('sub', 'Subscription')], default='sub', max_length=20),
        ),
    ]
