# Generated by Django 5.0.14 on 2026-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
