# Generated by Django 5.0.14 on 2026-03-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_form_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('form_type', 'type', 'order')},
        ),
    ]
