# Generated by Django 5.0.14 on 2026-03-14 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebooking',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_booking', to='services.booking'),
        ),
        migrations.AlterField(
            model_name='individualbooking',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_booking', to='services.booking'),
        ),
        migrations.AlterField(
            model_name='workplacegovernancebooking',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workplace_governance_booking', to='services.booking'),
        ),
    ]
