# Generated by Django 5.0.14 on 2026-03-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_make_booking_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('workforce_size', models.CharField(blank=True, choices=[('1-50', '1–50 employees'), ('51-200', '51–200 employees'), ('201-500', '201–500 employees'), ('500+', '500+ employees')], max_length=20)),
                ('challenge', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
